# config/packages/framework.yaml

framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    router:
        utf8: true
    annotations: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
