security:
    enable_authenticator_manager: true

    # Password Hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User Providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: /

    access_control:
        # Allow public access to homepage and trick details
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/trick, roles: PUBLIC_ACCESS }
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
        
        # Protect admin/dashboard or future private pages
        # - { path: ^/profile, roles: ROLE_USER }
        # - { path: ^/dashboard, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
