home:
    path: /
    controller: App\Controller\HomeController::index
trick_details:
    path: /trick/{slug}
    controller: App\Controller\TrickController::details
registration:
    path: /inscription
    controller: App\Controller\RegistrationController::register
