home:
    path: /
    controller: App\Controller\HomeController::index

registration:
    path: /inscription
    controller: App\Controller\RegistrationController::register

registration_confirmation:
    path: /inscription/confirmation
    controller: App\Controller\RegistrationController::confirmation

verify_email:
    path: /verify-email/{token}
    controller: App\Controller\RegistrationController::verifyEmail

app_login:
    path: /connexion
    controller: App\Controller\SecurityController::login

app_logout:
    path: /deconnexion

load_more_tricks:
    path: /load-more-tricks/{offset}
    controller: App\Controller\HomeController::loadMore
    requirements:
        offset: \d+

forgot_password:
    path: /mot-de-passe-oublie
    controller: App\Controller\SecurityController::forgotPassword

reset_password:
    path: /reinitialiser-mot-de-passe/{token}
    controller: App\Controller\SecurityController::resetPassword

trick_create:
    path: /trick/create
    controller: App\Controller\TrickController::create
    methods: [GET, POST]

trick_delete:
    path: /trick/{slug}/delete
    controller: App\Controller\TrickController::delete
    methods: [GET]
    requirements:
        slug: '[a-z0-9-]+'

trick_details:
    path: /trick/{slug}
    controller: App\Controller\TrickController::details
    methods: [GET]
    requirements:
        slug: '[a-z0-9-]+'

trick_edit:
    path: /trick/{slug}/edit
    controller: App\Controller\TrickController::edit
    methods: [GET, POST]
    requirements:
        slug: '[a-z0-9-]+'

trick_post_message:
    path: /trick/{slug}/message
    controller: App\Controller\TrickController::postMessage
    methods: [POST]
    requirements:
        slug: '[a-z0-9-]+'

media_delete_image:
    path: /trick/{trick_slug}/delete-image/{image_id}
    controller: App\Controller\MediaController::deleteImage
    methods: [GET]
    requirements:
        trick_slug: '[a-z0-9-]+'
        image_id: '\d+'

media_edit_image:
    path: /trick/{trick_slug}/edit-image/{image_id}
    controller: App\Controller\MediaController::editImage
    methods: [POST]
    requirements:
        trick_slug: '[a-z0-9-]+'
        image_id: '\d+'

media_add_image:
    path: /trick/{trick_slug}/add-media/image
    controller: App\Controller\MediaController::addMediaImage
    methods: [POST]
    requirements:
        trick_slug: '[a-z0-9-]+'

media_delete_video:
    path: /trick/{trick_slug}/delete-video/{video_id}
    controller: App\Controller\MediaController::deleteVideo
    methods: [GET]
    requirements:
        trick_slug: '[a-z0-9-]+'
        video_id: '\d+'

media_edit_video:
    path: /trick/{trick_slug}/edit-video/{video_id}
    controller: App\Controller\MediaController::editVideo
    methods: [POST]
    requirements:
        trick_slug: '[a-z0-9-]+'
        video_id: '\d+'

media_add_video:
    path: /trick/{trick_slug}/add-media/video
    controller: App\Controller\MediaController::addMediaVideo
    methods: [POST]
    requirements:
        trick_slug: '[a-z0-9-]+'

user_photo:
    path: /user/photo/{id}
    controller: App\Controller\UserController::photo
    methods: [GET]
