home:
    path: /
    controller: App\Controller\HomeController::index

registration:
    path: /inscription
    controller: App\Controller\RegistrationController::register

registration_confirmation:
    path: /inscription/confirmation
    controller: App\Controller\RegistrationController::confirmation

verify_email:
    path: /verify-email/{token}
    controller: App\Controller\RegistrationController::verifyEmail

app_login:
    path: /connexion
    controller: App\Controller\SecurityController::login

app_logout:
    path: /deconnexion

load_more_tricks:
    path: /load-more-tricks/{offset}
    controller: App\Controller\HomeController::loadMore
    requirements:
        offset: \d+

forgot_password:
    path: /mot-de-passe-oublie
    controller: App\Controller\SecurityController::forgotPassword

reset_password:
    path: /reinitialiser-mot-de-passe/{token}
    controller: App\Controller\SecurityController::resetPassword

trick_create:
    path: /trick/create
    controller: App\Controller\TrickController::create
    methods: [GET, POST]
    
trick_details:
    path: /trick/{slug}
    controller: App\Controller\TrickController::details
    methods: [GET]
    requirements:
        slug: '[a-z0-9-]+'

trick_delete_image:
    path: /trick/{trick_slug}/delete-image/{image_id}
    controller: App\Controller\TrickController::deleteImage
    methods: [GET]
    requirements:
        trick_slug: '[a-z0-9-]+'
        image_id: '\d+'
